# Generated by Django 5.1.6 on 2025-02-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_faq_alter_detaildescription_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detaildescription',
            name='lesson',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
    ]
