# Generated by Django 5.1.6 on 2025-02-14 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_lesson_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='video_url',
        ),
    ]
