# Generated by Django 5.1.6 on 2025-02-19 14:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='name_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название:'),
        ),
        migrations.AddField(
            model_name='blog',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название:'),
        ),
        migrations.AddField(
            model_name='blog',
            name='rich_ky',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='blog',
            name='rich_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='detaildescription',
            name='text_ky',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='detaildescription',
            name='text_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ky',
            field=models.TextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='name_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название:'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название:'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='rich_ky',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='rich_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
