# Generated by Django 5.1.6 on 2025-02-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_name_ky_blog_name_ru_blog_rich_ky_blog_rich_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Название:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название:'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название:'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Название:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название:'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название:'),
        ),
    ]
