# Generated by Django 5.1.6 on 2025-02-21 04:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blog_name_alter_blog_name_ky_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания:'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='rich',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание:'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='rich_ky',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание:'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='rich_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание:'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания:'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='rich',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание:'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='rich_ky',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание:'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='rich_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание:'),
        ),
    ]
