# Generated by Django 5.1.6 on 2025-02-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='name_ky',
            new_name='title_ky',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='name_ru',
            new_name='title_ru',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='name_ky',
            new_name='title_ky',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='name_ru',
            new_name='title_ru',
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Название:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Название:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название:'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название:'),
        ),
    ]
