# Generated by Django 5.1.6 on 2025-03-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_rename_name_ky_blog_title_ky_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeChannelSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=100, verbose_name='ID канала YouTube')),
                ('api_key', models.CharField(max_length=100, verbose_name='API ключ YouTube')),
                ('auto_import', models.BooleanField(default=True, verbose_name='Автоматический импорт')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
            ],
            options={
                'verbose_name': 'Настройки YouTube канала',
                'verbose_name_plural': 'Настройки YouTube каналов',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='YouTube ID'),
        ),
    ]
