# Generated by Django 5.1.6 on 2025-02-14 18:55

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_client_options_alter_manager_options_and_more'),
        ('tour', '0006_hotel_category_packagedetail_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-created_at'], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'ordering': ['user__username'], 'verbose_name': 'Менеджер', 'verbose_name_plural': 'Менеджеры'},
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='client',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_clients', to='crm.manager', verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='client',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='tour.package', verbose_name='Выбранный пакет'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Пример: +996555123456', max_length=128, region='KG', verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('processing', 'В обработке'), ('no_answer', 'Не дозвон'), ('thinking', 'Думает'), ('rejected', 'Отклонено'), ('success', 'Успешно')], db_index=True, default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Пример: +996555123456', max_length=128, region='KG', verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='telegram_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
