# Generated by Django 5.1.6 on 2025-02-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_client_options_alter_manager_options_and_more'),
        ('tour', '0006_hotel_category_packagedetail_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['status', 'created_at'], name='crm_client_status_e982f2_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['manager', 'status'], name='crm_client_manager_ff9239_idx'),
        ),
    ]
