# Generated by Django 5.1.6 on 2025-02-28 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='branch',
            field=models.CharField(choices=[('Bishkek', 'Бишкек'), ('Osh', 'Ош')], default='Bishkek', max_length=100, verbose_name='Филиал'),
        ),
    ]
