# Generated by Django 5.1.6 on 2025-03-03 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_alter_manager_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
    ]
