# Generated by Django 5.1.6 on 2025-03-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_client_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='user',
        ),
        migrations.AddField(
            model_name='manager',
            name='full_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Полное имя'),
            preserve_default=False,
        ),
    ]
