# Generated by Django 5.1.6 on 2025-02-11 10:15

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ajy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО:')),
                ('bio', ckeditor.fields.RichTextField(verbose_name='Биография:')),
                ('image', models.ImageField(upload_to='', verbose_name='Фотография:')),
            ],
            options={
                'verbose_name': 'Ажы',
                'verbose_name_plural': 'Ажы',
            },
        ),
        migrations.CreateModel(
            name='CategoryPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название:')),
            ],
            options={
                'verbose_name': 'Категория пакета',
                'verbose_name_plural': 'Категории пакетов',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название:')),
                ('city', models.CharField(choices=[('mecca', 'Мекка'), ('medina', 'Медина')], max_length=10, verbose_name='Город:')),
                ('stars', models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], default=5, verbose_name='Звёздность отеля')),
                ('distance_to_mosque', models.CharField(help_text='Например: 300 м', max_length=100, verbose_name='Расстояние до мечети:')),
                ('accommodation', models.CharField(help_text='Например: Четырехместное', max_length=100, verbose_name='Размещение:')),
                ('meals', models.CharField(blank=True, help_text='Например: Завтрак и ужин шведский стол', max_length=200, null=True, verbose_name='Питание:')),
                ('nights', models.PositiveIntegerField(blank=True, help_text='Необязательное поле', null=True, verbose_name='Количество ночей:')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
            },
        ),
        migrations.CreateModel(
            name='PackageDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название:')),
                ('rich', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка:')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
                ('detail_type', models.CharField(choices=[('FoodInfo', 'Информация о питании'), ('Requirements', 'Рекомендуется'), ('Restrictions', 'Не рекомендуется'), ('PlacesToVisit', 'Места для посещения'), ('YouGet', 'Что вы получите от нас')], max_length=100, verbose_name='Тип информации:')),
            ],
            options={
                'verbose_name': 'Детали пакета',
                'verbose_name_plural': 'Детали пакетов',
                'ordering': ['detail_type'],
            },
        ),
        migrations.CreateModel(
            name='TourDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_tour', models.DateTimeField(verbose_name='Дата начало:')),
                ('end_tour', models.DateTimeField(verbose_name='Дата конец:')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Название:')),
                ('image', models.ImageField(upload_to='packages/', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание:')),
                ('available_seats', models.PositiveIntegerField(default=0, verbose_name='Макс. мест')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('ajy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='tour.ajy', verbose_name='Ажы башчы')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='tour.categorypackage', verbose_name='Категория')),
                ('tour_date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='tour.tourdate', verbose_name='Дата тура')),
            ],
            options={
                'verbose_name': 'Пакет',
                'verbose_name_plural': 'Пакеты',
            },
        ),
    ]
