# Generated by Django 5.1.6 on 2025-02-14 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagedetail',
            name='video_url',
        ),
    ]
