# Generated by Django 5.1.6 on 2025-02-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_packagedetail_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ImageField(upload_to='packages/images/', verbose_name='Изображение'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['city', 'stars'], name='tour_hotel_city_254a6f_idx'),
        ),
    ]
