# Generated by Django 5.1.6 on 2025-02-14 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_alter_hotel_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='package_hotels', to='tour.categorypackage', verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagedetail',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='package_details', to='tour.categorypackage', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
