# Generated by Django 5.1.6 on 2025-02-19 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_hotel_category_packagedetail_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotels/images/', verbose_name='Изображение')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_images', to='tour.hotel', verbose_name='Отель')),
            ],
            options={
                'verbose_name': 'Изображение отеля',
                'verbose_name_plural': 'Изображения отелей',
            },
        ),
    ]
