# Generated by Django 5.1.6 on 2025-02-22 11:00

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0008_ajy_bio_ky_ajy_bio_ru_ajy_name_ky_ajy_name_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageDetailImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название:')),
                ('rich', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка:')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
                ('package_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_detail_images', to='tour.packagedetail', verbose_name='Детали пакета')),
            ],
            options={
                'verbose_name': 'Изображение детали пакета',
                'verbose_name_plural': 'Изображения деталей пакетов',
            },
        ),
    ]
