# Generated by Django 5.1.6 on 2025-02-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0009_packagedetailimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='place',
            field=models.CharField(choices=[('Bishkek', 'Бишкек'), ('Osh', 'Ош')], default=1, max_length=100, verbose_name='Филиал:'),
            preserve_default=False,
        ),
    ]
