# Generated by Django 5.1.6 on 2025-03-03 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0010_package_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourdate',
            options={'verbose_name': 'Тур дата', 'verbose_name_plural': 'Туры даты'},
        ),
        migrations.AddField(
            model_name='package',
            name='package_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='package_details', to='tour.packagedetail', verbose_name='Детали пакетов'),
            preserve_default=False,
        ),
    ]
