# Generated by Django 5.1.6 on 2025-03-06 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0011_alter_tourdate_options_package_package_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='package_detail',
        ),
    ]
