# Generated by Django 5.1.6 on 2025-03-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0012_remove_package_package_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelimage',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
