# Generated by Django 5.1.6 on 2025-03-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0013_hotelimage_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Пример: 21.422487 (Мекка)', max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Пример: 39.826206 (Мекка)', max_digits=9, null=True, verbose_name='Долгота'),
        ),
    ]
