# Generated by Django 5.1.6 on 2025-03-06 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0014_hotel_latitude_hotel_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='longitude',
        ),
    ]
