# Generated by Django 5.1.6 on 2025-03-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0015_remove_hotel_latitude_remove_hotel_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='addres_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на карту'),
        ),
    ]
